/*
 * RunwalkVideoAboutBox.java
 */

package com.runwalk.video.gui;

import java.awt.Frame;

import javax.swing.JButton;

import net.miginfocom.swing.MigLayout;

import org.jdesktop.application.Action;

@SuppressWarnings("serial")
public class RunwalkVideoAboutDialog extends AppDialog implements AppComponent {

    private JButton closeButton;
	
	public RunwalkVideoAboutDialog(Frame parent) {
        super(parent);
        initComponents();
        getRootPane().setDefaultButton(closeButton);
    }

    @Action 
    public void closeAboutBox() {
        setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	setLayout(new MigLayout());
        closeButton = new javax.swing.JButton();
        javax.swing.JLabel appTitleLabel = new javax.swing.JLabel();
        javax.swing.JLabel versionLabel = new javax.swing.JLabel();
        javax.swing.JLabel appVersionLabel = new javax.swing.JLabel();
        javax.swing.JLabel vendorLabel = new javax.swing.JLabel();
        javax.swing.JLabel appVendorLabel = new javax.swing.JLabel();
        javax.swing.JLabel homepageLabel = new javax.swing.JLabel();
        javax.swing.JLabel appHomepageLabel = new javax.swing.JLabel();
        javax.swing.JLabel appDescLabel = new javax.swing.JLabel();
        javax.swing.JLabel imageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        setResizable(false);

        closeButton.setAction(getAction("closeAboutBox")); // NOI18N

        appTitleLabel.setFont(appTitleLabel.getFont().deriveFont(appTitleLabel.getFont().getStyle() | java.awt.Font.BOLD, appTitleLabel.getFont().getSize()+4));
        appTitleLabel.setText(getResourceMap().getString("Application.title")); // NOI18N
        add(appTitleLabel, "wrap");
        
        versionLabel.setFont(versionLabel.getFont().deriveFont(versionLabel.getFont().getStyle() | java.awt.Font.BOLD));
        versionLabel.setText(getResourceMap().getString("versionLabel.text")); // NOI18N
        add(versionLabel);

        appVersionLabel.setText(getResourceMap().getString("Application.version")); // NOI18N
        add(appVersionLabel, "wrap");

        vendorLabel.setFont(vendorLabel.getFont().deriveFont(vendorLabel.getFont().getStyle() | java.awt.Font.BOLD));
        vendorLabel.setText(getResourceMap().getString("vendorLabel.text")); // NOI18N
        appVendorLabel.setText(getResourceMap().getString("Application.vendor")); // NOI18N
        add(vendorLabel, "wrap");

        homepageLabel.setFont(homepageLabel.getFont().deriveFont(homepageLabel.getFont().getStyle() | java.awt.Font.BOLD));
        homepageLabel.setText(getResourceMap().getString("homepageLabel.text")); // NOI18N
        add(homepageLabel);
        
        appHomepageLabel.setText(getResourceMap().getString("Application.homepage")); // NOI18N
        appDescLabel.setText(getResourceMap().getString("appDescLabel.text")); // NOI18N
        add(homepageLabel, "wrap");
        
        imageLabel.setIcon(getResourceMap().getIcon("imageLabel.icon")); // NOI18N
        add(imageLabel, "wrap");

        add(closeButton);
        pack();
    }
    
}
